### GridSearchCV and Hyperparameter for SVM (Support Vector Machine)

Problem Steatemnt: classificatin problem using SVM Algo, and selecting hyperpameter using gridsearchCV to improve model performance.

Gridsearch applied on any Machine Learning Classification Algorithm

Process of choosign optimal parameter is called Hyperparameter Tuning

- First we apply algo without tuning Hyperparamet and check the Accuracy.
- Then we will perform Hyperameter tuning and check the accuracy

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Importing Data set

In [2]:
df=pd.read_csv('C://Users//553341//Desktop//krish//Advertising_data.csv')
df.head()

User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [13]:
df.shape

(400, 5)

#### Dividing data into dependent and Independent category

In [3]:
x=df.iloc[:,2:4]
y=df.iloc[:,-1]

In [30]:
q=df.iloc[:,4].values  # return data 1D Array form
q=df.iloc[:,4]        # data in series form


array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [31]:
e=df.iloc[:,[2,4]].values  # we we are selecting 2 column so we get 2D Array

### Splitting Dataset into Train and Test.
To do so we require train_tets_split library from sklearn.model_selection

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=5)

### Feature Scaling
- Here we are using Algo SVM which perfom by calculating distance. If there are huge scale difference between feature then we    must perform feature scaling.
- we are going to use StandardScaler wiich will scale down the data using Standar Normal Distribution

In [5]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#### Now we are going to apply SVM Algo on data(X_train)

In [6]:
#fitting kernel SVM to training Data set
from sklearn.svm import SVC
classifier=SVC(kernel='linear', random_state=0)  #kernel='linear' : a linear line will seperate two vectors
classifier.fit(X_train,y_train)

SVC(kernel='linear', random_state=0)

In [7]:
 #Now we will predict test reslut
y_pred=classifier.predict(X_test)

In [10]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[60  6]
 [ 9 25]]


In [11]:
# Now test the accuracy
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,y_pred)

In [12]:
accuracy

0.85

In [13]:
# till here we have used default parameter of SVC Algo and got 85% Accuracy

In [22]:
#Apply Grid Serch to find the best modelnad the best parameter

from sklearn.model_selection import GridSearchCV
parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)

In [25]:
accuracy=grid_search.best_score_

In [26]:
#this is grid_search accuracy, do not consider it model accuracy
accuracy

0.9100000000000001

In [27]:
#it is very important to know on which parameter we are getting best score.
grid_search.best_params_

{'C': 10, 'gamma': 0.3, 'kernel': 'rbf'}

### Now by usign gridSearchCV we have got  best parameters.
We will use these paramter to pass in Algo and get the same accuracy

In [31]:
classifier=SVC(kernel='rbf', gamma=0.3)  #kernel='linear' : a linear line will seperate two vectors
classifier.fit(X_train,y_train)

SVC(gamma=0.3)

In [32]:
y_pred=classifier.predict(X_test)

In [33]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[61  5]
 [ 3 31]]


In [34]:
# tis is my model accuracy
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.92